apiVersion: apps/v1
kind: Deployment
metadata: # name of the deployment
  name: gateway
spec:
  replicas: 1 # number of pods to create
  selector:
    matchLabels: # all pods that have the label app name 'ping' are belonged to 'ping-deployment'
      app: gateway
  template: # template of pods (all pods have same configuration)
    metadata:
      labels: # each app gets the same label (i.e., ping in our case)
        app: gateway
    spec:
      containers: # name of the container
      - name: gateway
        image: final-proj-gateway:001 # docker image with tag
        resources:
          limits:
            memory: "512Mi"
            cpu: "600m"
        ports:
        - containerPort: 9696 # port to expose
        env :
           - name: TF_SERVING_HOST
             value: tf-serving-chestxray-model.default.svc.cluster.local:8500

