apiVersion: apps/v1
kind: Deployment
metadata: # name of the deployment
  name: tf-serving-chestxray-model
spec:
  replicas: 1 # number of pods to create
  selector:
    matchLabels: 
      app: tf-serving-chestxray-model
  template: # template of pods (all pods have same configuration)
    metadata:
      labels: # each app gets the same label (i.e., ping in our case)
        app: tf-serving-chestxray-model
    spec:
      containers: # name of the container
      - name: tf-serving-chestxray-model
        image: final-proj-model:resnet50-v2-001 # docker image with tag
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        ports:
        - containerPort: 8500 # port to expose

